LOAD DATA LOCAL INFILE './users.txt' INTO TABLE users FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE './recipes.txt' INTO TABLE recipes FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE './ingredientslist.txt' INTO TABLE recipeIngredients FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE './bookmarks.txt' INTO TABLE bookmarks FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE './reviews.txt' INTO TABLE reviews FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';